<?php

defined('ABSPATH') || exit;

return array(
    array('legacy_sku' => 'SL-BULB-0001', 'sku' => 'SL-BULB-0001', 'name' => 'Bóng đèn LED thông minh SmartLife 9W', 'category' => 'Bóng đèn thông minh', 'price' => 199000),
    array('legacy_sku' => 'SL-PROD-0002', 'sku' => 'SL-BULB-0002', 'name' => 'Bóng đèn LED thông minh SmartLife 7W', 'category' => 'Bóng đèn thông minh', 'price' => 149000),
    array('legacy_sku' => 'SL-PROD-0003', 'sku' => 'SL-BULB-0003', 'name' => 'Bóng đèn LED thông minh SmartLife 12W', 'category' => 'Bóng đèn thông minh', 'price' => 179000),
    array('legacy_sku' => 'SL-PROD-0004', 'sku' => 'SL-BULB-0004', 'name' => 'Bóng đèn LED thông minh SmartLife 15W', 'category' => 'Bóng đèn thông minh', 'price' => 199000),
    array('legacy_sku' => 'SL-PROD-0005', 'sku' => 'SL-LED-0001', 'name' => 'Đèn LED thông minh SmartLife RGB', 'category' => 'Đèn LED thông minh', 'price' => 229000),
    array('legacy_sku' => 'SL-PROD-0006', 'sku' => 'SL-LED-0002', 'name' => 'Đèn LED thông minh SmartLife 20W', 'category' => 'Đèn LED thông minh', 'price' => 249000),
    array('legacy_sku' => 'SL-PROD-0007', 'sku' => 'SL-NIGHT-0001', 'name' => 'Đèn ngủ thông minh SmartLife', 'category' => 'Đèn ngủ thông minh', 'price' => 299000),
    array('legacy_sku' => 'SL-PROD-0008', 'sku' => 'SL-CAM-0001', 'name' => 'Camera Wi-Fi thông minh SmartLife Full HD', 'category' => 'Camera thông minh', 'price' => 499000),
    array('legacy_sku' => 'SL-PROD-0009', 'sku' => 'SL-CAM-0002', 'name' => 'Camera trong nhà SmartLife 2MP', 'category' => 'Camera thông minh', 'price' => 599000),
    array('legacy_sku' => 'SL-PROD-0010', 'sku' => 'SL-CAM-0003', 'name' => 'Camera ngoài trời SmartLife', 'category' => 'Camera thông minh', 'price' => 699000),
    array('legacy_sku' => 'SL-PROD-0011', 'sku' => 'SL-CAM-0004', 'name' => 'Camera an ninh SmartLife 3MP', 'category' => 'Camera thông minh', 'price' => 799000),
    array('legacy_sku' => 'SL-PROD-0012', 'sku' => 'SL-DOORBELL-0001', 'name' => 'Chuông cửa thông minh SmartLife', 'category' => 'Chuông cửa thông minh', 'price' => 899000),
    array('legacy_sku' => 'SL-PROD-0013', 'sku' => 'SL-DOORBELL-0002', 'name' => 'Chuông cửa camera SmartLife', 'category' => 'Chuông cửa thông minh', 'price' => 999000),
    array('legacy_sku' => 'SL-PROD-0014', 'sku' => 'SL-LOCK-0001', 'name' => 'Khóa cửa thông minh SmartLife', 'category' => 'Khóa cửa thông minh', 'price' => 1299000),
    array('legacy_sku' => 'SL-PROD-0015', 'sku' => 'SL-LOCK-0002', 'name' => 'Khóa cửa vân tay SmartLife', 'category' => 'Khóa cửa thông minh', 'price' => 1499000),
    array('legacy_sku' => 'SL-PROD-0016', 'sku' => 'SL-SECURITY-0001', 'name' => 'Cảm biến an ninh SmartLife', 'category' => 'Cảm biến an ninh', 'price' => 1699000),
    array('legacy_sku' => 'SL-PROD-0017', 'sku' => 'SL-SWITCH-0001', 'name' => 'Công tắc thông minh SmartLife 1 nút', 'category' => 'Công tắc thông minh', 'price' => 1899000),
    array('legacy_sku' => 'SL-PROD-0018', 'sku' => 'SL-SWITCH-0002', 'name' => 'Công tắc thông minh SmartLife 2 nút', 'category' => 'Công tắc thông minh', 'price' => 2199000),
    array('legacy_sku' => 'SL-PROD-0019', 'sku' => 'SL-SWITCH-0003', 'name' => 'Công tắc thông minh SmartLife 3 nút', 'category' => 'Công tắc thông minh', 'price' => 2499000),
    array('legacy_sku' => 'SL-PROD-0020', 'sku' => 'SL-SOCKET-0001', 'name' => 'Ổ cắm thông minh SmartLife Wi-Fi', 'category' => 'Ổ cắm thông minh', 'price' => 299000),
    array('legacy_sku' => 'SL-PROD-0021', 'sku' => 'SL-SOCKET-0002', 'name' => 'Ổ cắm thông minh SmartLife 16A', 'category' => 'Ổ cắm thông minh', 'price' => 349000),
    array('legacy_sku' => 'SL-PROD-0022', 'sku' => 'SL-HUB-0001', 'name' => 'Hub điều khiển SmartLife Zigbee', 'category' => 'Hub điều khiển', 'price' => 399000),
    array('legacy_sku' => 'SL-PROD-0023', 'sku' => 'SL-HUB-0002', 'name' => 'Hub nhà thông minh SmartLife', 'category' => 'Hub điều khiển', 'price' => 499000),
    array('legacy_sku' => 'SL-PROD-0024', 'sku' => 'SL-REMOTE-0001', 'name' => 'Remote thông minh SmartLife', 'category' => 'Remote thông minh', 'price' => 599000),
    array('legacy_sku' => 'SL-PROD-0025', 'sku' => 'SL-ROBOT-0001', 'name' => 'Robot hút bụi SmartLife', 'category' => 'Robot hút bụi', 'price' => 699000),
    array('legacy_sku' => 'SL-PROD-0026', 'sku' => 'SL-ROBOT-0002', 'name' => 'Robot hút bụi lau nhà SmartLife', 'category' => 'Robot hút bụi', 'price' => 799000),
    array('legacy_sku' => 'SL-PROD-0027', 'sku' => 'SL-AIRPURIFIER-0001', 'name' => 'Máy lọc không khí SmartLife', 'category' => 'Máy lọc không khí', 'price' => 999000),
    array('legacy_sku' => 'SL-PROD-0028', 'sku' => 'SL-AIRPURIFIER-0002', 'name' => 'Máy lọc không khí SmartLife Pro', 'category' => 'Máy lọc không khí', 'price' => 1299000),
    array('legacy_sku' => 'SL-PROD-0029', 'sku' => 'SL-DEHUMIDIFIER-0001', 'name' => 'Máy hút ẩm thông minh SmartLife', 'category' => 'Máy hút ẩm', 'price' => 1499000),
    array('legacy_sku' => 'SL-PROD-0030', 'sku' => 'SL-CURTAIN-0001', 'name' => 'Rèm cửa thông minh SmartLife', 'category' => 'Rèm cửa thông minh', 'price' => 1799000),
    array('legacy_sku' => 'SL-PROD-0031', 'sku' => 'SL-MOTION-0001', 'name' => 'Cảm biến chuyển động SmartLife', 'category' => 'Cảm biến chuyển động', 'price' => 1990000),
    array('legacy_sku' => 'SL-PROD-0032', 'sku' => 'SL-DOOR-0001', 'name' => 'Cảm biến cửa SmartLife', 'category' => 'Cảm biến cửa', 'price' => 2290000),
    array('legacy_sku' => 'SL-PROD-0033', 'sku' => 'SL-TEMP-0001', 'name' => 'Cảm biến nhiệt độ SmartLife', 'category' => 'Cảm biến nhiệt độ và độ ẩm', 'price' => 2490000),
    array('legacy_sku' => 'SL-PROD-0034', 'sku' => 'SL-TEMP-0002', 'name' => 'Cảm biến nhiệt độ và độ ẩm SmartLife', 'category' => 'Cảm biến nhiệt độ và độ ẩm', 'price' => 2990000),
    array('legacy_sku' => 'SL-PROD-0035', 'sku' => 'SL-SMOKE-0001', 'name' => 'Cảm biến khói SmartLife', 'category' => 'Cảm biến khói', 'price' => 3490000),
    array('legacy_sku' => 'SL-PROD-0036', 'sku' => 'SL-WIFI-0001', 'name' => 'Bộ phát Wi-Fi SmartLife', 'category' => 'Bộ phát Wi-Fi', 'price' => 3990000),
    array('legacy_sku' => 'SL-PROD-0037', 'sku' => 'SL-WIFI-0002', 'name' => 'Bộ phát Wi-Fi Mesh SmartLife', 'category' => 'Bộ phát Wi-Fi', 'price' => 4990000),
    array('legacy_sku' => 'SL-PROD-0038', 'sku' => 'SL-CONTROLLER-0001', 'name' => 'Bộ điều khiển trung tâm SmartLife', 'category' => 'Bộ điều khiển trung tâm', 'price' => 5990000),
    array('legacy_sku' => 'SL-PROD-0039', 'sku' => 'SL-ACCESSORY-0001', 'name' => 'Bộ phụ kiện nhà thông minh SmartLife', 'category' => 'Phụ kiện nhà thông minh', 'price' => 6990000),
    array('legacy_sku' => 'SL-PROD-0040', 'sku' => 'SL-ACCESSORY-0002', 'name' => 'Bộ điều khiển hồng ngoại SmartLife', 'slug' => 'bo-dieu-khien-hong-ngoai-smartlife', 'category' => 'Phụ kiện nhà thông minh', 'price' => 7990000),
);
